### ISSUE TITLE
Интеграция с IDE

### ISSUE THREAD

**Issue by Neliitsme** [kysect/AssignmentReporter#11]
Было бы неплохо сделать расширения для известных идешек с возможностью выбора загружаемых файлов и написания мини отчёта по проделанной работе. 

Как часть геймификации можно даже сделать внизу окошко для оставления комментариев студентом по поводу лабораторной и/или добавить возможность оценки лабораторной от :( до :)  (или пятибалльная шкала).

Как опция, можно ещё сделать окно переписки преподавателя со студентом на случай возникновения вопросов у студента по поводу лабораторной или преподавателем на случай вопросов по поводу выполненной работы.

**Comment by Neliitsme** [comment]
Я вероятно запутался в проектах, поэтому написал в том, который выглядит наиболее связанным с этим

**Comment by TomGnill** [comment]
Я недавно написал плагин для вижлы, который может составить отчёт для репозитория, могу его сюда интегрировать, там только придётся немного доработать интерфейс и логику.
