### ISSUE TITLE
Реализовать white- и blacklist для файлов

### ISSUE THREAD

**Issue by FrediKats** [kysect/AssignmentReporter#3]
При генерации отчетов должна быть возможность выгружать
- только файлы по указанной маске вайтлиста
- все файлы помимо указанных в блеклисте

Есть смысл поддержать либо маски, лабо искать подсроками. Также, хотелось бы добавить шаблонные листы. Например, для VS было бы неплохо всегда игнорировать .git, bin/, obj/, .csproj

**Comment by Bibletoon** [comment]
А если вы стильный, модный, молодежный, прогрессивный, хайповый, нейтральный и вот это все, можете реализовать allow- и denylist
